kind: PersistentVolume
apiVersion: v1
metadata:
  name: tekton-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/containers"
  persistentVolumeReclaimPolicy: Retain

